# Generated by Django 3.2.9 on 2021-12-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='subcategory',
            field=models.CharField(default=(('Bakery', ('cake', 'cookies', 'bread', 'pies', 'pizza')), ('rice', ('jollof rice', 'fried rice', 'chinese rice', 'rice & stew', 'coconut rice')), ('roast', ('corn', 'beans & roasted plantain', 'bole', 'roasted chicken')), ('barbeque', ('grilled chicken', 'grilled beef', 'grilled fish', 'suya')), ('sharwarma', ('chicken', 'beef', 'chicken jumbo+2hotdog', 'beef jumbo+2hotdog'))), max_length=100),
        ),
    ]
