# Generated by Django 3.2.9 on 2021-12-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211211_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name': 'catergory', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Food', 'verbose_name_plural': 'Foods'},
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='name',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='categorie',
            name='subcategory',
            field=models.CharField(default=(('Bakery', ('cake', 'cookies', 'bread', 'pies', 'pizza')), ('rice', ('jollof rice', 'fried rice', 'chinese rice', 'rice & stew', 'coconut rice')), ('roast', ('corn', 'beans & roasted plantain', 'bole', 'roasted chicken')), ('barbeque', ('grilled chicken', 'grilled beef', 'grilled fish', 'suya')), ('sharwarma', ('chicken', 'beef', 'chicken jumbo+2hotdog', 'beef jumbo+2hotdog'))), max_length=100, unique=True),
        ),
    ]
