# Generated by Django 3.2.9 on 2021-12-11 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('staus', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('is_active', models.BooleanField()),
                ('order_no', models.IntegerField(default=order.models.generate_order_no, editable=False, primary_key=True, serialize=False, unique=True)),
                ('unit', models.IntegerField(default=0)),
                ('price', models.PositiveIntegerField()),
                ('order', models.CharField(max_length=100)),
                ('order_date', models.DateField(auto_now=True)),
                ('completed', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
