# Generated by Django 3.2.9 on 2021-12-19 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_food_image'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='main.food'),
        ),
    ]
