# Generated by Django 3.2.9 on 2021-12-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
